### ISSUE TITLE
Generating new binding_affinity.pt files

### ISSUE THREAD

**Issue by slochower** [Rose-STL-Lab/LIMO#1]
Hi. In the README, you write:

> The default binding affinity model is ESR1 (which is `binding_affinity.pt`), but to optimize binding to another protein one must make sure the `binding_affinity.pt` file contains the model for that correct protein. 

Can you describe a bit more how you generate the file `binding_affinity.pt` for a new protein? Thanks!

**Comment by PeterEckmann1** [comment]
Hi, thanks for your interest! `binding_affinity.pt`is a pytorch model file, so it will require retraining of the property predictor (see https://github.com/Rose-STL-Lab/LIMO#training-the-property-predictor). 

If you have a new protein, first you need to prepare files for docking with AutoDock-GPU. Instructions for that can be found at: https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/AutoDock4.2.6_UserGuide.pdf starting at page 13. Once you have all the files that are needed (it should look similar to the files in https://github.com/Rose-STL-Lab/LIMO/tree/main/1err), put them in a folder in the main directory and then call `python train_property_predictor.py --prop binding_affinity --protein_file <folder name>/<protein name>.maps.fld`. When the training is done, a new `binding_affinity.pt` file will be saved, and you should be ready to generate molecules!

Let me know if you need any assistance during this process, I'm happy to help :)
