### ISSUE TITLE
PyTorch Lightning Version

### ISSUE THREAD

**Issue by mikelee-dev** [Rose-STL-Lab/LIMO#11]
Hi!
Would it be possible for you to share which version of PyTorch Lightning you used? 

It seems that a lot of functionality in PyTorch Lightning has been deprecated as of version 2.0, which is causing some breaking.
I have been able to solve some changes by searching for how to handle the deprecated funtionalities, but it would be easier to reproduce the code if the PyTorch Lightning version number was known

For example in line 46 of train_property_predictory.py: ```trainer = pl.Trainer(gpus=1, max_epochs=5, logger=pl.loggers.CSVLogger('logs'), enable_checkpointing=False, auto_lr_find=True)``` The attribute ```gpus``` does not exist in the Trainer class anymore for PyTorch version 2.0 
- ``gpus`` can be replaced by adding ``accelerator='gpu'`` and ``devices=1``
- There are some more cases, so it would be helpful to just use the same package version for better reproducibility of the code
 
 Thanks for your help!

**Comment by PeterEckmann1** [comment]
Thanks for pointing that out! I used version 1.9.0, and I've now updated requirements.txt to reflect that: https://github.com/Rose-STL-Lab/LIMO/commit/18fb3805b9789b22bb9f371fe989405128137717
