### ISSUE TITLE
Why is the data presented in the code I run different from what is presented in the paper. Could you help me take a look

### ISSUE THREAD

**Issue by zhanghan1234** [Rose-STL-Lab/LIMO#13]
parser.add_argument('--prop', choices=['logp', 'penalized_logp', 'qed', 'sa', 'binding_affinity', 'multi_objective_binding_affinity'], default='qed')
parser.add_argument('--num_mols', type=int, default=100000)
parser.add_argument('--top_k', type=int, default=3)
parser.add_argument('--sa_cutoff', type=float, default=5.5)
parser.add_argument('--qed_cutoff', type=float, default=0.4)
parser.add_argument('--optim_steps', type=int, default=22)#原来是10
parser.add_argument('--autodock_executable', type=str, default='AutoDock-GPU/bin/autodock_gpu_128wi')#这个必须有
parser.add_argument('--protein_file', type=str, default='1err/1err.maps.fld')#这个必须指定，还可以换成2iik/2iik.maps.fld
args = parser.parse_args()
These are the hyperparameter I use, vae.pt and qed.pt are provided by you

**Comment by zhanghan1234** [comment]
Table1

**Comment by PeterEckmann1** [comment]
Thanks for your interest in the paper! I'd need some more details before I can say why your results are different. What results are you currently getting for the QED task? I would expect some small variations from the numbers in the paper, but a large difference would indicate something else is going on.

**Comment by zhanghan1234** [comment]
> Thanks for your interest in the paper! I'd need some more details before I can say why your results are different. What results are you currently getting for the QED task? I would expect some small variations from the numbers in the paper, but a large difference would indicate something else is going on.

python generate_molecules.py --prop penalized_logp
generating molecules: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:38<00:00,  9.82s/it]
16.639477 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC1CC1
16.639477 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC1CC1
17.468054 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC=CCC


python generate_molecules.py --prop qed
generating molecules: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:35<00:00,  9.54s/it]
calculating QED: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:14<00:00, 671.45it/s]
0.8635939 CC=CC1=CC1NC(=O)C2CCCCCCCC3=CC=CC=C23
0.8734434 CC=CC1=CC1NC(=O)C2CCCC=CC=CC3=CC=CC=C23
0.88593656 CC=CC1=CC1NC(=O)C2CC=CC=CC=CC3=CC=CC=C23
Hello. This is the result of my run. I did not change the hyperparameter, but directly used the provided code to get the hyperparameter. I didn't train my own VAE model, but instead used the provided VAE.PT and the provided QED.PT. Can you help me check which step I made a mistake.
