### ISSUE TITLE
table1&2

### ISSUE THREAD

**Issue by zhanghan1234** [Rose-STL-Lab/LIMO#14]
python generate_molecules.py --prop penalized_logp
generating molecules: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:38<00:00, 9.82s/it]
16.639477 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC1CC1
16.639477 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC1CC1
17.468054 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC=CCC

python generate_molecules.py --prop qed
generating molecules: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:35<00:00, 9.54s/it]
calculating QED: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:14<00:00, 671.45it/s]
0.8635939 CC=CC1=CC1NC(=O)C2CCCCCCCC3=CC=CC=C23
0.8734434 CC=CC1=CC1NC(=O)C2CCCC=CC=CC3=CC=CC=C23
0.88593656 CC=CC1=CC1NC(=O)C2CC=CC=CC=CC3=CC=CC=C23
Hello. This is the result of my run. I did not change the hyperparameter, but directly used the provided code to get the hyperparameter. I didn't train my own VAE model, but instead used the provided VAE.PT and the provided QED.PT. Can you help me check which step I made a mistake.

**Comment by PeterEckmann1** [comment]
Hi, sorry for the very late reply! I must have missed your issue when it was first posted. If you're still interested in getting this to work, the first thing I would try would be to set `--num_mols 100000`, since for logP and QED we used 100,000 compounds for the tables. That will likely get you a lot closer to the results in the paper, but let me know if it's still not close and we can see what else might be going on.

**Comment by zhanghan1234** [comment]
Thanks



发自我的iPhone


------------------ Original ------------------
From: PeterEckmann1 ***@***.***&gt;
Date: Wed,Oct 4,2023 9:49 AM
To: Rose-STL-Lab/LIMO ***@***.***&gt;
Cc: zhanghan1234 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Rose-STL-Lab/LIMO] table1&amp;2 (Issue #14)





 
Hi, sorry for the very late reply! I must have missed your issue when it was first posted. If you're still interested in getting this to work, the first thing I would try would be to set --num_mols 100000, since for logP and QED we used 100,000 compounds for the tables. That will likely get you a lot closer to the results in the paper, but let me know if it's still not close and we can see what else might be going on.
