### ISSUE TITLE
Docking Scores for ACAA1 and ESR1

### ISSUE THREAD

**Issue by mikelee-dev** [Rose-STL-Lab/LIMO#16]
Hi Peter,

Would you happen to have docking scores saved for these 2 receptors? I would like to retrain the property predictors for binding affinity without re-computing docking scores. Perhaps a csv file formatted like, (smiles, docking score)

Thanks!

**Comment by PeterEckmann1** [comment]
Sure, here you go! This file contains scores for both ESR1 and ACAA1, for 10000 random molecules generated from the VAE:
[precomputed_affinities.csv](https://github.com/Rose-STL-Lab/LIMO/files/12992447/precomputed_affinities.csv)

**Comment by mikelee-dev** [comment]
Thanks so much! I appreciate it.

Best,
Michael
