### ISSUE TITLE
About property computation

### ISSUE THREAD

**Issue by tszslovewanpu** [Rose-STL-Lab/LIMO#17]
Hello, and great job! I have a question regarding property computation.
For instance, in Table 1, how do we compute the PENALIZED LOGP and QED for the generated molecules using different methods?
Do we employ RDKit or the trained property prediction model gθ?
If we use the property prediction model gθ, how do other methods compute their properties?
Do they calculate the PENALIZED LOGP and QED using their own respective property prediction models?(if so, how about the fairity)
Thank you very much!

**Comment by PeterEckmann1** [comment]
Hi,

Thanks for your interest! The penalized logP and QED property computation is done using RDKit for all methods. The property prediction models are only used in the generation process, not the actual evaluation. Therefore, the outputs from `generate_molecules.py` are computed using RDKit.

**Comment by tszslovewanpu** [comment]
Got it, thanks!
