### ISSUE TITLE
About the metric

### ISSUE THREAD

**Issue by tszslovewanpu** [Rose-STL-Lab/LIMO#21]
Hello, i'm back again~

Take **_logp targetting_** as an example：

I generated molecules with a total count of **_N_**, where **_N1_** are the molecules that meets the condition _logp in (-2.5, -2)_.
**_M_** are the molecules in **_N_** that are duplicates of the training set, and _**N2**_ are the molecules that meet the criterion in **_(N-M)_**.

When calculating the proportion of molecules falling within the desired range for the logP targeting task, which of the following ratios should be used?
- N1/N
- N2/(N-M)
- N2/N

When calculating the similarity between generated molecules, which set should be used for this calculation?
- N
- N-M
- N1
- N2

Thank you!

**Comment by tszslovewanpu** [comment]
![example](https://github.com/Rose-STL-Lab/LIMO/assets/117994206/03063721-a9de-43e7-af65-8bbc287223d4)

**Comment by PeterEckmann1** [comment]
Hi, N1/N would be the correct ratio. We didn't take into account the training set at all when calculating the proportion of molecules in the desired range. And for the similarity calculation, we used the N1 set, because what we're interested in is how diverse the molecules are that meet the condition. Let me know if you have any more questions!

**Comment by tszslovewanpu** [comment]
Thank you!
Happy children's day~

**Comment by tszslovewanpu** [comment]
Dear Peter:
By the way, have you encountered a situation where there are invalid molecules in N? Should I include them when calculating the proportion? (I generated some invalud molecules, and don't know how to deal with them, include them or not. TAT) Thank you~
Best wishes ^v^

**Comment by PeterEckmann1** [comment]
Hmm, not sure if I've seen that, since I thought SELFIES always decodes to valid SMILES. Can you send me an example? But in general, I would probably exclude them, since you can't calculate logP on them.

**Comment by tszslovewanpu** [comment]
Hi, dear Peter:
I used a different representation that can be converted to SELFIES and then to SMILES. For example, there are elements like [Br1] and [@H1], I think it would be fairer to include these in the denominator N, as some methods generate 100% valid molecules, while mine do not.
Thank you!

**Comment by PeterEckmann1** [comment]
Ah okay, that makes sense. Then yes, I think you're right that including them in the denominator would make sense.
