### ISSUE TITLE
About the Substructure-constrained logP Extremization task

### ISSUE THREAD

**Issue by tszslovewanpu** [Rose-STL-Lab/LIMO#22]
Dear Peter,

I'm back again. Could you please send me the two molecules (SMILES or SELFIES) and the selected substructure for TASK 4.5: Substructure-constrained logP Extremization? Thank you!

Best regards,
Fan

**Comment by PeterEckmann1** [comment]
Hi Fan, sure, you can find the SMILES here along with the associated substructures: https://github.com/Rose-STL-Lab/LIMO/issues/9#issuecomment-1402727348

**Comment by tszslovewanpu** [comment]
❤
