### ISSUE TITLE
The code runs very slowly after this point “subprocess.run(f'{autodock} -M {protein_file} -s 0 -L ligands/0/ligand0.pdbqt -N outs/ligand0', shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)”

### ISSUE THREAD

**Issue by renyongqi529** [Rose-STL-Lab/LIMO#4]
I see nvidia-smi is GPU-Util:0%,but Memory-Usage  is used. I have AutoDock-GPU installed and it compiles fine.Please give me some pointers, thanks.

**Comment by PeterEckmann1** [comment]
Hi, could you try removing `stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL` and paste what output you get? It's possible autodock is giving some errors that are being piped to DEVNULL.
