### ISSUE TITLE
Script to reproduce Table 1&2

### ISSUE THREAD

**Issue by mxc19912008** [Rose-STL-Lab/LIMO#5]
Hi, 

Thanks for the great contribution!

May I ask if the code to reproduce Table 1 and Table 2 is released? 

Thanks!

**Comment by PeterEckmann1** [comment]
@mxc19912008 Could you get the code working for those tables? If you're still interested I can give some guidance. The first table should be relatively easy to reproduce using `--prop penalized_logp`. The second table is bit more involved, but is still possible with the current code.
